// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxVQ6JXQ3gsoO8WYx6heNoS2t93tpg3vY',
    appId: '1:886366280169:web:dcca7b6d1a87e79b8d1378',
    messagingSenderId: '886366280169',
    projectId: 'learn-connect-51a0d',
    authDomain: 'learn-connect-51a0d.firebaseapp.com',
    storageBucket: 'learn-connect-51a0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn0nO4-S5ZuPAK0qx0e_E7EsP05gOUkT8',
    appId: '1:886366280169:android:6b73e5534ba4e6ea8d1378',
    messagingSenderId: '886366280169',
    projectId: 'learn-connect-51a0d',
    storageBucket: 'learn-connect-51a0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM1qFKBNk5BNS6tlyd8XPdeQ8IDNsrEms',
    appId: '1:886366280169:ios:f19f0cd91309e8388d1378',
    messagingSenderId: '886366280169',
    projectId: 'learn-connect-51a0d',
    storageBucket: 'learn-connect-51a0d.firebasestorage.app',
    iosBundleId: 'com.example.learnConnect',
  );
}
